### ISSUE TITLE
IE compatibility 

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#219] opened 2017-05-03 18:58 UTC
With our new opportunity in mind I think we should consider adding proper IE support.
I think this would make are product much more interesting.

Let's discuss @outcobra/developers

**Comment by needToRoll** [comment] 2017-05-03 19:02
it would be nice if we could open our product without it falling apart. (At the meeting)

**Comment by M4R1KU** [comment] 2017-05-03 19:03
Why me again? Am I only one that can deal with frontend?

needToRoll <notifications@github.com> schrieb am Mi., 3. Mai 2017, 20:58:

**Comment by needToRoll** [comment] 2017-05-03 19:05
As you can see, I assigned all of us I just want to hear your opinions and your thoughts regarding priority

**Comment by jmesserli** [comment] 2017-05-03 19:08
I don't think we should support IE because of the same reasons that we decided against it in the first place. What we should do though is make our app at least start in IE.

**Comment by M4R1KU** [comment] 2017-05-03 19:33
Ups, I did not see that bc I was too lazy to open github

Joel Messerli <notifications@github.com> schrieb am Mi., 3. Mai 2017, 21:08:

**Comment by M4R1KU** [comment] 2017-05-04 18:48
Agreed @jmesserli

**Comment by jmesserli** [comment] 2017-06-02 12:46
Duplicate of #217

**Closed by jmesserli** 2017-06-02 12:46 UTC
Labels: M-C-frontend, T-discussion, T-enhancement
