### ISSUE TITLE
all input values are parsed to dates if possible

### ISSUE THREAD

**Issue by needToRoll** [outcobra/outstanding-cobra#185] opened 2017-04-02 11:09 UTC
When a user creates an object and inserts a number (or something else that can be converted to a date), we convert it into a date. This can lead to strange results!

![image](https://cloud.githubusercontent.com/assets/22860045/24586607/4c038c2e-17a5-11e7-9f1b-e4076d8757b1.png)

We need to find a way how we can find out if a field should be converted or not.

**Comment by jmesserli** [comment] 2017-04-02 12:00
We just have to only parse ISO formatted dates, that'd be the easiest way.

**Comment by M4R1KU** [comment] 2017-04-16 11:15
Now I parse only dates which match the format `YYYY-MM-DD` that fixes all problems except if for instance an institution is named in exactly this format. Most likely that will never happen in real life but it's still an issue that itches me.

**Comment by jmesserli** [comment] 2017-04-16 11:49
maybe we need to approach this differently then, but I don't have an idea yet

**Comment by M4R1KU** [comment] 2017-04-16 11:50
do you know an existing application that does that?

**Comment by jmesserli** [comment] 2017-04-16 11:54
There should be a lot of apps handling dates in the wild... Can't think of a specific one right now

**Comment by M4R1KU** [comment] 2017-04-16 19:04
It is shit to fix this issue except we use custom date and time objects (My solution does not work).
The problem is that `JSON.stringify` first runs the `toJSON` method on the Date object and then the date object is not a date object anymore so it is not convenient to identify it as such and even if I transform it to a moment i won't know how to use it (time or date).

So I think we wait until the MdDatepicker because it will bring custom date and time objects which we then can use and will make the work on this issue a lot lot lot lot lot easier.

Another option would be to take the date code from the current version of the MdDatepicker and use it until we will change to the provided one.

**Comment by M4R1KU** [comment] 2017-06-05 18:57
The `stringify` is easy to fix and it is currently fixed on #243.
But the `parse` is quite hard because I the `dateReviver` is not aware whether the JSON attribute should be handled as date. So if a user does name his institution `2017-06-02` (or similar) the string will be parsed to a date even if it is actually the name. It is very unlikely that a user will name anything like this but you'll never know.

Do you have an idea how we could distinct between dates and not date attributes? @needToRoll @jmesserli

**Comment by jmesserli** [comment] 2017-06-06 15:35
The easiest fix would be to parse dates in the respective components that need them (datepicker)

**Comment by M4R1KU** [comment] 2017-06-07 12:04
I've done it this way but it is actually kind of ugly

**Comment by jmesserli** [comment] 2017-08-10 13:48
Fixed according to @M4R1KU

**Closed by jmesserli** 2017-08-10 13:48 UTC
Labels: M-C-frontend, P-2-high, T-bug
