### ISSUE TITLE
Calendar opening on the wrong month

### ISSUE THREAD

**Issue by jmesserli** [outcobra/outstanding-cobra#270] opened 2017-08-09 17:17 UTC
When a date was selected and the calendar is reopened, it seems like the day is treated as the month.

![image](https://user-images.githubusercontent.com/613138/29134569-5b22ad5a-7d37-11e7-84ef-b6727a7d224c.png)

**Comment by M4R1KU** [comment] 2017-08-09 17:22
Duplicate of #250

**Comment by jmesserli** [comment] 2017-08-09 17:23
My bad

**Closed** 2017-08-09 17:23 UTC
Labels: M-C-frontend, P-3-medium, T-bug
